### ISSUE TITLE
Students' Lives Matter

### ISSUE THREAD

**Issue by woshoxxx** [woshoxxx/woshixxx#2]
https://697slm.icu/error=redirect_uri_mismatch&error_description=The%2Bredirect_uri%2BMUST%2Bmatch%2Bthe%2Bregistered%2Bcallback%2BURL%2Bfor%2Bthis%2Bapplication.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

**Comment by woshoxxx** [comment]
测试

**Comment by 697slmicu** [comment]
这是一个测试。

**Comment by woshoxxx** [comment]
哈喽，我是聊天室的管理员！🤭

**Comment by 697slmicu** [comment]
这是一个测试。表示聊天室系统已经正常使用。

**Comment by woshoxxx** [comment]
> @697slmicu
> 这是一个测试。表示聊天室系统已经正常使用。

那个，等会我关掉这个聊天室，然后你点开启，这样你就有删除评论的权限了

**Comment by RuangFeng** [comment]
好活当赏

**Comment by woshoxxx** [comment]
> @RuangFeng
> 好活当赏

哈哈哈，之前一直没明白这个系统怎么在博客上用，今天终于弄明白了，也派上用场了
